export const COUNTRIES = [
  { code: 'US', name: 'United States', capital: 'Washington, D.C.' },
  { code: 'GB', name: 'United Kingdom', capital: 'London' },
  { code: 'JP', name: 'Japan', capital: 'Tokyo' },
  { code: 'CA', name: 'Canada', capital: 'Ottawa' },
  { code: 'AU', name: 'Australia', capital: 'Canberra' },
  { code: 'DE', name: 'Germany', capital: 'Berlin' },
  { code: 'FR', name: 'France', capital: 'Paris' },
  { code: 'IT', name: 'Italy', capital: 'Rome' },
  { code: 'BR', name: 'Brazil', capital: 'Brasília' },
  { code: 'IN', name: 'India', capital: 'New Delhi' },
  { code: 'CN', name: 'China', capital: 'Beijing' },
  { code: 'RU', name: 'Russia', capital: 'Moscow' },
  { code: 'ZA', name: 'South Africa', capital: 'Pretoria' },
  { code: 'MX', name: 'Mexico', capital: 'Mexico City' },
  { code: 'ES', name: 'Spain', capital: 'Madrid' },
  { code: 'KR', name: 'South Korea', capital: 'Seoul' },
  { code: 'ID', name: 'Indonesia', capital: 'Jakarta' },
  { code: 'TR', name: 'Turkey', capital: 'Ankara' },
  { code: 'SA', name: 'Saudi Arabia', capital: 'Riyadh' },
  { code: 'AR', name: 'Argentina', capital: 'Buenos Aires' },
  { code: 'EG', name: 'Egypt', capital: 'Cairo' },
  { code: 'NG', name: 'Nigeria', capital: 'Abuja' },
  { code: 'SE', name: 'Sweden', capital: 'Stockholm' },
  { code: 'NO', name: 'Norway', capital: 'Oslo' },
  { code: 'FI', name: 'Finland', capital: 'Helsinki' },
  { code: 'DK', name: 'Denmark', capital: 'Copenhagen' },
  { code: 'NL', name: 'Netherlands', capital: 'Amsterdam' },
  { code: 'BE', name: 'Belgium', capital: 'Brussels' },
  { code: 'CH', name: 'Switzerland', capital: 'Bern' },
  { code: 'AT', name: 'Austria', capital: 'Vienna' },
  { code: 'PL', name: 'Poland', capital: 'Warsaw' },
  { code: 'PT', name: 'Portugal', capital: 'Lisbon' },
  { code: 'GR', name: 'Greece', capital: 'Athens' },
  { code: 'IE', name: 'Ireland', capital: 'Dublin' },
  { code: 'NZ', name: 'New Zealand', capital: 'Wellington' },
  { code: 'SG', name: 'Singapore', capital: 'Singapore' },
  { code: 'MY', name: 'Malaysia', capital: 'Kuala Lumpur' },
  { code: 'TH', name: 'Thailand', capital: 'Bangkok' },
  { code: 'VN', name: 'Vietnam', capital: 'Hanoi' },
  { code: 'PH', name: 'Philippines', capital: 'Manila' },
  { code: 'PK', name: 'Pakistan', capital: 'Islamabad' },
  { code: 'BD', name: 'Bangladesh', capital: 'Dhaka' },
  { code: 'IR', name: 'Iran', capital: 'Tehran' },
  { code: 'IQ', name: 'Iraq', capital: 'Baghdad' },
  { code: 'IL', name: 'Israel', capital: 'Jerusalem' },
  { code: 'AE', name: 'United Arab Emirates', capital: 'Abu Dhabi' },
  { code: 'CO', name: 'Colombia', capital: 'Bogotá' },
  { code: 'CL', name: 'Chile', capital: 'Santiago' },
  { code: 'PE', name: 'Peru', capital: 'Lima' },
  { code: 'VE', name: 'Venezuela', capital: 'Caracas' },
  { code: 'MA', name: 'Morocco', capital: 'Rabat' },
  { code: 'DZ', name: 'Algeria', capital: 'Algiers' },
  { code: 'KE', name: 'Kenya', capital: 'Nairobi' },
  { code: 'ET', name: 'Ethiopia', capital: 'Addis Ababa' },
  { code: 'GH', name: 'Ghana', capital: 'Accra' },
  { code: 'UA', name: 'Ukraine', capital: 'Kyiv' },
  { code: 'RO', name: 'Romania', capital: 'Bucharest' },
  { code: 'HU', name: 'Hungary', capital: 'Budapest' },
  { code: 'CZ', name: 'Czech Republic', capital: 'Prague' },
  { code: 'SK', name: 'Slovakia', capital: 'Bratislava' },
  { code: 'RS', name: 'Serbia', capital: 'Belgrade' },
  { code: 'HR', name: 'Croatia', capital: 'Zagreb' },
  { code: 'BG', name: 'Bulgaria', capital: 'Sofia' },
  { code: 'SI', name: 'Slovenia', capital: 'Ljubljana' },
  { code: 'LT', name: 'Lithuania', capital: 'Vilnius' },
  { code: 'LV', name: 'Latvia', capital: 'Riga' },
  { code: 'EE', name: 'Estonia', capital: 'Tallinn' },
  { code: 'IS', name: 'Iceland', capital: 'Reykjavik' },
  { code: 'CR', name: 'Costa Rica', capital: 'San José' },
  { code: 'PA', name: 'Panama', capital: 'Panama City' },
  { code: 'DO', name: 'Dominican Republic', capital: 'Santo Domingo' },
  { code: 'CU', name: 'Cuba', capital: 'Havana' }
];